[INFO] 2019-01-13 00:33:45,551 >>	[START]  Processor.preprocess()
[INFO] 2019-01-13 00:33:45,551 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 00:33:53,191 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:07
[INFO] 2019-01-13 00:33:53,191 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 00:33:59,487 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:06
[INFO] 2019-01-13 00:33:59,488 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 00:34:07,120 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:07
[INFO] 2019-01-13 00:34:07,120 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 00:34:13,515 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:06
[INFO] 2019-01-13 00:34:13,516 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 00:34:21,140 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:07
[INFO] 2019-01-13 00:34:21,140 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 00:34:27,466 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:06
[INFO] 2019-01-13 00:34:27,467 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 00:34:35,942 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:08
[INFO] 2019-01-13 00:34:35,942 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 00:34:42,359 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:06
[INFO] 2019-01-13 00:34:42,360 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 00:34:50,066 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:07
[INFO] 2019-01-13 00:34:50,066 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 00:34:56,518 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:06
[INFO] 2019-01-13 00:34:56,519 >>	[FINISH] Processor.preprocess(): [elapsed_time] >> 00:01:10
[ERROR] 2019-01-13 00:34:56,519 >>	Unexpected Exception Occurred.
Traceback (most recent call last):
  File "src/main.py", line 20, in <module>
    main(get_option())
  File "src/main.py", line 12, in main
    ProcessorFactory.process(args)
  File "/Users/berry/Kaggle/malware/src/processor_factory.py", line 32, in process
    validity, predict = processor.process()
  File "/Users/berry/Kaggle/malware/src/processor.py", line 32, in process
    assert False
AssertionError
